In [5]:
import pandas as pd
df = pd.read_csv('final_dataset.csv', low_memory=False)

numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns
print(numeric_columns)

df.head()

Index(['academicYear', 'idOSYM', 'scholarshipRate', 'quota', 'occupiedSlots',
       'tuitionFee', 'profCount', 'assoCount', 'docCount', 'baseRanking',
       'topRanking', 'avgAdmissionRanking', 'baseAdmissionRanking',
       'stdDeviationStudents', 'revenue', 'outOfCityStudentRate',
       'totalPreference', 'top1PreferenceRatio', 'avgOrderofPreference',
       'avgAdmittedStudentPrefOrder', 'top1AdmittedRatio', 'top3AdmittedRatio',
       'top10AdmittedRatio', 'admittedTotalPref',
       'admittedTotalDepartmentPref', 'currentStudentCount', 'baseScore',
       'topScore', 'totalForeignStudents', 'totalStudentNumber', 'Urap_Rank',
       'Urap_Score', 'avg_monthly_income_group', 'Time_for_employment',
       'employment_rate', 'base_salary_by_year', 'inflation_by_year',
       'growth_by_year'],
      dtype='object')

,academicYear,universityName,universityType,faculty,departmentName,idOSYM,programType,language,scholarshipRate,quota,...,totalForeignStudents,totalStudentNumber,Urap_Rank,Urap_Score,avg_monthly_income_group,Time_for_employment,employment_rate,base_salary_by_year,inflation_by_year,growth_by_year
0,2023,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,mimarlıkfakültesi,mimarlık,106510014.0,SAY,İngilizce,0.0,70,...,235.0,2670.0,50.0,705.460000,-1.0,11.3,79.2,11402,64.0,3.8
1,2022,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,mimarlıkfakültesi,mimarlık,106510014.0,SAY,İngilizce,0.0,70,...,235.0,2670.0,43.0,716.794001,-2.0,11.8,76.9,5500,64.0,5.4
2,2024,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,mimarlıkfakültesi,mimarlık,106510014.0,SAY,İngilizce,0.0,60,...,235.0,2670.0,58.0,617.880000,-1.0,11.3,79.2,17002,64.0,2.7
3,2020,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,mimarlıkfakültesi,mimarlık,106510014.0,SAY,İngilizce,0.0,62,...,235.0,2670.0,36.0,521.630000,-2.0,11.8,76.9,2103,14.0,1.8
4,2019,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,mimarlıkfakültesi,mimarlık,106510014.0,SAY,İngilizce,0.0,62,...,235.0,2670.0,26.0,551.940000,-2.0,11.8,76.9,2103,11.8,0.7

## Conversion to Numeric Columns

In [6]:
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns

non_numeric_counts = {}
missing_counts = {}

for col in numeric_columns:
    non_numeric_counts[col] = df[col].apply(pd.to_numeric, errors='coerce').isnull().sum()
    missing_counts[col] = df[col].isnull().sum()

# Print non-numeric and missing value counts
print("Non-numeric value counts in numeric columns:")
print(non_numeric_counts)
print("\nMissing value counts in numeric columns:")
print(missing_counts)

# Get summary statistics for numeric columns
summary_statistics = df[numeric_columns].describe()
print("\nSummary statistics for numeric columns:")
print(summary_statistics)

Non-numeric value counts in numeric columns:
{'academicYear': np.int64(0), 'idOSYM': np.int64(0), 'scholarshipRate': np.int64(0), 'quota': np.int64(0), 'occupiedSlots': np.int64(0), 'tuitionFee': np.int64(0), 'profCount': np.int64(0), 'assoCount': np.int64(0), 'docCount': np.int64(0), 'baseRanking': np.int64(0), 'topRanking': np.int64(0), 'avgAdmissionRanking': np.int64(0), 'baseAdmissionRanking': np.int64(0), 'stdDeviationStudents': np.int64(0), 'revenue': np.int64(0), 'outOfCityStudentRate': np.int64(0), 'totalPreference': np.int64(0), 'top1PreferenceRatio': np.int64(0), 'avgOrderofPreference': np.int64(0), 'avgAdmittedStudentPrefOrder': np.int64(0), 'top1AdmittedRatio': np.int64(0), 'top3AdmittedRatio': np.int64(0), 'top10AdmittedRatio': np.int64(0), 'admittedTotalPref': np.int64(0), 'admittedTotalDepartmentPref': np.int64(0), 'currentStudentCount': np.int64(0), 'baseScore': np.int64(0), 'topScore': np.int64(0), 'totalForeignStudents': np.int64(0), 'totalStudentNumber': np.int64(0), 'Urap_Rank': np.int64(0), 'Urap_Score': np.int64(0), 'avg_monthly_income_group': np.int64(0), 'Time_for_employment': np.int64(0), 'employment_rate': np.int64(0), 'base_salary_by_year': np.int64(0), 'inflation_by_year': np.int64(0), 'growth_by_year': np.int64(0)}

Missing value counts in numeric columns:
{'academicYear': np.int64(0), 'idOSYM': np.int64(0), 'scholarshipRate': np.int64(0), 'quota': np.int64(0), 'occupiedSlots': np.int64(0), 'tuitionFee': np.int64(0), 'profCount': np.int64(0), 'assoCount': np.int64(0), 'docCount': np.int64(0), 'baseRanking': np.int64(0), 'topRanking': np.int64(0), 'avgAdmissionRanking': np.int64(0), 'baseAdmissionRanking': np.int64(0), 'stdDeviationStudents': np.int64(0), 'revenue': np.int64(0), 'outOfCityStudentRate': np.int64(0), 'totalPreference': np.int64(0), 'top1PreferenceRatio': np.int64(0), 'avgOrderofPreference': np.int64(0), 'avgAdmittedStudentPrefOrder': np.int64(0), 'top1AdmittedRatio': np.int64(0), 'top3AdmittedRatio': np.int64(0), 'top10AdmittedRatio': np.int64(0), 'admittedTotalPref': np.int64(0), 'admittedTotalDepartmentPref': np.int64(0), 'currentStudentCount': np.int64(0), 'baseScore': np.int64(0), 'topScore': np.int64(0), 'totalForeignStudents': np.int64(0), 'totalStudentNumber': np.int64(0), 'Urap_Rank': np.int64(0), 'Urap_Score': np.int64(0), 'avg_monthly_income_group': np.int64(0), 'Time_for_employment': np.int64(0), 'employment_rate': np.int64(0), 'base_salary_by_year': np.int64(0), 'inflation_by_year': np.int64(0), 'growth_by_year': np.int64(0)}

Summary statistics for numeric columns:
       academicYear        idOSYM  scholarshipRate         quota  \
count  50554.000000  5.055400e+04     50554.000000  50554.000000
mean    2021.723286  1.444653e+08        27.103197     47.995628
std        1.665723  4.817297e+07        39.955394     87.623558
min     2019.000000  1.001100e+08         0.000000      3.000000
25%     2020.000000  1.048102e+08         0.000000     16.000000
50%     2022.000000  1.094102e+08         0.000000     40.000000
75%     2023.000000  2.027106e+08        50.000000     62.000000
max     2024.000000  2.104028e+08       100.000000   5800.000000

       occupiedSlots     tuitionFee     profCount     assoCount      docCount  \
count   50554.000000   50554.000000  50554.000000  50554.000000  50554.000000
mean       45.230664   22034.506246      4.673498      2.485204      4.966392
std        83.293915   65423.419840     16.066785      5.958231      7.891802
min         0.000000       0.000000      0.000000      0.000000      0.000000
25%        10.000000       0.000000      0.000000      0.000000      2.000000
50%        36.000000       0.000000      2.000000      1.000000      3.000000
75%        62.000000       0.000000      4.000000      3.000000      5.000000
max      5945.000000  945000.000000    321.000000    106.000000    110.000000

        baseRanking  ...  totalForeignStudents  totalStudentNumber  \
count  5.055400e+04  ...          50554.000000        50554.000000
mean   3.488528e+05  ...           1870.983265        14664.071053
std    4.155182e+05  ...           2229.616073        10267.674970
min    2.400000e+01  ...              0.000000            0.000000
25%    7.576925e+04  ...            424.000000         6535.000000
50%    2.292760e+05  ...           1154.000000        12694.000000
75%    4.706222e+05  ...           2186.000000        21157.000000
max    3.527443e+06  ...          15755.000000        43610.000000

          Urap_Rank    Urap_Score  avg_monthly_income_group  \
count  50554.000000  50554.000000              50554.000000
mean      73.825454    507.146698                 -0.323693
std       53.215191    227.151211                  1.226699
min        0.000000      0.000000                 -2.000000
25%       27.000000    373.790000                 -1.000000
50%       65.000000    501.560000                 -0.347491
75%      118.000000    654.930000                  0.000000
max      190.000000   1126.410000                  2.000000

       Time_for_employment  employment_rate  base_salary_by_year  \
count         50554.000000     50554.000000         50554.000000
mean             13.659821        76.170569          7413.000633
std               3.833788         9.177941          5696.306368
min               2.300000        39.700000          2103.000000
25%              11.300000        70.900000          2103.000000
50%              13.600000        75.838320          5500.000000
75%              16.300000        83.400000         11402.000000
max              24.500000        96.200000         17002.000000

       inflation_by_year  growth_by_year
count       50554.000000    50554.000000
mean           45.248938        4.492252
std            22.300975        3.493843
min            11.800000        0.700000
25%            14.000000        1.800000
50%            64.000000        3.800000
75%            64.000000        5.400000
max            64.000000       11.600000

[8 rows x 38 columns]

## Encoding

In [7]:
from category_encoders.target_encoder import TargetEncoder
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# One-hot encoding
one_hot_columns = ['universityType', 'programType', 'language']
df = pd.get_dummies(df, columns=one_hot_columns)

# Label encoding
label_columns = ['universityLocation', 'universityRegion','universityName', 'departmentName', 'faculty']
label_encoder = LabelEncoder()
for col in label_columns:
    df[col] = label_encoder.fit_transform(df[col])

# Ordinal encoding for ordinal features
ordinal_mapping = {
    'scholarshipRate': {0.0: 0, 25.0: 1, 50.0: 2, 75.0: 3, 100.0: 4},
}
for col, mapping in ordinal_mapping.items():
    if col in df.columns:
        df[col] = df[col].map(mapping)

non_numeric_columns = df.select_dtypes(exclude=['number']).columns
print(non_numeric_columns)

Index(['universityType_devlet', 'universityType_vakıf', 'programType_DİL',
       'programType_EA', 'programType_SAY', 'programType_SÖZ',
       'language_Almanca', 'language_Arapça', 'language_Bulgarca',
       'language_Ermenice', 'language_Fransızca', 'language_Korece',
       'language_Lehçe', 'language_Rusça', 'language_Türkçe', 'language_Çince',
       'language_İngilizce', 'language_İspanyolca', 'language_İtalyanca'],
      dtype='object')

In [8]:
for col in non_numeric_columns:
    df[col] = df[col].astype(int)
non_numeric_columns = df.select_dtypes(exclude=['number']).columns
print(non_numeric_columns)
df.head()
df.to_csv('final_dataset_encoded.csv', index=False)

Index([], dtype='object')